-- ==========================================
-- PERFORMANCE OPTIMIZATION: ADDING INDEXES
-- ==========================================
-- Supabase (Postgres) does not automatically create indexes for foreign keys.
-- When the app joins tables (e.g. vessel_members to profiles) without indexes,
-- Postgres must perform a "Sequential Scan", checking every row in the table.
-- As the app grows, this causes extremely high Disk I/O and CPU usage.
-- This script creates the missing indexes to make reads O(1) or O(log n).

-- 1. Index for vessel_members
-- Very frequently queried to find all crew for a specific vessel.
CREATE INDEX IF NOT EXISTS idx_vessel_members_vessel_id ON public.vessel_members(vessel_id);
-- Frequently queried to find which vessel a user belongs to.
CREATE INDEX IF NOT EXISTS idx_vessel_members_user_id ON public.vessel_members(user_id);

-- 2. Index for join_requests
-- Queried by the captain to see pending requests for their vessel.
CREATE INDEX IF NOT EXISTS idx_join_requests_vessel_id ON public.join_requests(vessel_id);
-- Queried efficiently if we ever need to find requests by user.
CREATE INDEX IF NOT EXISTS idx_join_requests_user_id ON public.join_requests(user_id);

-- 3. Index for schedules
-- Queried constantly to fetch the active schedule for a vessel.
CREATE INDEX IF NOT EXISTS idx_schedules_vessel_id ON public.schedules(vessel_id);

-- 4. Index for profiles
-- If we do fast lookups by assigned vessel ID.
CREATE INDEX IF NOT EXISTS idx_profiles_vessel_id ON public.profiles(vessel_id);

-- Note: user_id is the primary key on `crew_secure_data` therefore it already 
-- has an implicit B-Tree index generated by Postgres.
-- The `captain_id` on `vessels` is also a good candidate for indexing.
CREATE INDEX IF NOT EXISTS idx_vessels_captain_id ON public.vessels(captain_id);
